create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id)
);

alter table public.admin_users enable row level security;
revoke all on table public.admin_users from public, anon, authenticated;
grant select, insert, update, delete on table public.admin_users to service_role;

create table if not exists public.inventory_adjustments (
  id bigint generated by default as identity primary key,
  sku text not null references public.inventory_items(sku),
  previous_stock integer not null check (previous_stock >= 0),
  new_stock integer not null check (new_stock >= 0),
  changed_by uuid not null references auth.users(id),
  changed_at timestamptz not null default now()
);

alter table public.inventory_adjustments enable row level security;
revoke all on table public.inventory_adjustments from public, anon, authenticated;
revoke all on sequence public.inventory_adjustments_id_seq from public, anon, authenticated;
grant select, insert on table public.inventory_adjustments to service_role;
grant usage, select on sequence public.inventory_adjustments_id_seq to service_role;

revoke insert, update, delete on table public.inventory_items from anon, authenticated;

create or replace function public.admin_set_inventory_stock(
  p_sku text,
  p_stock_quantity integer,
  p_admin_user_id uuid
)
returns table (sku text, stock_quantity integer)
language plpgsql
security invoker
set search_path = ''
as $$
declare
  previous_quantity integer;
begin
  if p_stock_quantity < 0 or p_stock_quantity > 100000 then
    raise exception 'INVALID_STOCK_QUANTITY';
  end if;

  if not exists (
    select 1
    from public.admin_users
    where user_id = p_admin_user_id
      and active = true
  ) then
    raise exception 'ADMIN_ACCESS_DENIED';
  end if;

  select item.stock_quantity
  into previous_quantity
  from public.inventory_items as item
  where item.sku = p_sku
  for update;

  if not found then
    raise exception 'INVENTORY_ITEM_NOT_FOUND';
  end if;

  update public.inventory_items as item
  set stock_quantity = p_stock_quantity,
      updated_at = now()
  where item.sku = p_sku;

  insert into public.inventory_adjustments (
    sku,
    previous_stock,
    new_stock,
    changed_by
  )
  values (
    p_sku,
    previous_quantity,
    p_stock_quantity,
    p_admin_user_id
  );

  return query select p_sku, p_stock_quantity;
end;
$$;

revoke all on function public.admin_set_inventory_stock(text, integer, uuid)
from public, anon, authenticated;
grant execute on function public.admin_set_inventory_stock(text, integer, uuid)
to service_role;

comment on table public.admin_users is
  'Server-only allowlist of Supabase Auth users with Hibiscus Group admin access.';
comment on table public.inventory_adjustments is
  'Immutable audit trail for stock changes made through the admin dashboard.';
